name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Application
        uses: actions/checkout@v3
  #       uses: appleboy/ssh-action@master
  #       with: 
  #         host: ${{ secrets.SSH_HOST }}
  #         key: ${{ secrets.SSH_KEY }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         script: |
  #           mkdir /test
  #           cd /test
  #           git clone git@github.com:shimar007/ci-cd-deploy-learning.git .
  #           echo "Successfully deployed"
  # merge_pull_request:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout main branch
  #       uses: actions/checkout@v2