name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Application
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/html/test
            git clone git@github.com:shimar007/ci-cd-deploy-learning.git
            echo "Successfully deployed"